{% set name = "pyupgrade" %}
{% set version = "1.16.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 327a851df76fc2bc86969c964928e7ed9e6a563fd78febd671047415257df21a

build:
  noarch: python
  number: 0
  entry_points:
    - pyupgrade = pyupgrade:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - tokenize-rt >=2.1

test:
  commands:
    - pyupgrade --help

about:
  home: https://github.com/asottile/pyupgrade
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool to automatically upgrade syntax for newer versions.

extra:
  recipe-maintainers:
    - nicoddemus
    - tadeu
