{% set name = "pyupgrade" %}
{% set version = "2.37.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3d9cbd88507a0f3d7397c46870617f0d073d61401c451c08a06763d6235d9e7d

build:
  noarch: python
  number: 0
  entry_points:
    - pyupgrade = pyupgrade._main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6.1
    - setuptools
  run:
    - python >=3.6.1
    - tokenize-rt >=3.2.0

test:
  commands:
    - pyupgrade --help

about:
  home: https://github.com/asottile/pyupgrade
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool to automatically upgrade syntax for newer versions.

extra:
  recipe-maintainers:
    - nicoddemus
    - tadeu
