{% set name = "pyupgrade" %}
{% set version = "2.30.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95c9986bff7f525b20986d6bd161bb14c223633a2035a292a8fa8f1936f3a7a4

build:
  noarch: python
  number: 0
  entry_points:
    - pyupgrade = pyupgrade._main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6.1
    - setuptools
  run:
    - python >=3.6.1
    - tokenize-rt >=3.2.0

test:
  commands:
    - pyupgrade --help

about:
  home: https://github.com/asottile/pyupgrade
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A tool to automatically upgrade syntax for newer versions.

extra:
  recipe-maintainers:
    - nicoddemus
    - tadeu
