travis:
  secure:
    BINSTAR_TOKEN: di7F3YP8MFHrVmLQM1iR3c6KO74rI6gfPFRpnaJPY/raQANjTmdFNK8Keupn+SphVgalB58nYKJE609QpURVB2Qif56jYop6jZbYy20Ts6fxhhqyouoCsSMWmRv0cHrxENJ1ANV0KOC7Dt+2vvF0UBPmBL4erSho4lFHFx3fdfCYPkExY+y2nymygs+0pd6d7d6ewg+r4rEOflfpW0q7cwhb2Gks2qYEraAJ9g01E9uPypbMO8ciRQF2yIlwG14mPpXrgNe5xpReSgCiXbBHxt+C72s2Js9qo9hfdAA06h3LLFoUDnSv/9J5KqmMqVbQpZyivLBMrTOJ+mnRnxYn4SeYg73PuFA11ypFfc+C+rwtipL4bNrgt79OoaZylHxcK6P+zqSuxERV/bXFLkBc9KVSkI4sPytZdvfJGNidVNOHi5daEXr8Y2FBLAa6JeWQ5Uyx8QxNEYcDILlvteYBQWOgbgcZogKSSzAsw+i+7UkmShr/8LjxpsksA6Aqm6r256YxPexy0O6RXXvAN1+x7ZfbSJ4ChG1EL2BHyrAoL/xnl2Ex6+N0OvjH6FAuNvSTFFt4llqiLVAzgSc9gcQ4t36sX2ro0DxZVIDWit8AkFc45xRC8ojAWsobmdg5eQlC8OXO9KBRChnFQugkFI2BoD8rH6UbABw1VF8ma3H357o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
