travis:
  secure:
    BINSTAR_TOKEN: hA/+xAr9JioAo87VHQTHQeqLuR932FJZmjpXaQegbQCaQUvgNOxpuoYDcOqeKTEUf34C47C6vvc8f4jYxtSSFA/j7Qh8H2Z49LhldC4KV8Aoz7uxc8zCaiKV+kV5xFjq8lf81sQyU6iIpzN75XlGddLbD78+EVtfwpuEptZTCQJYFpVlnR0zbYeXrXJeOyRR3OAo6fVWkg79MjwW37JB/4+Yj7dXwmj7qYg42MPydQtEtpKvH0ncCCedmByFvglmaZJIggd/YIQxnTE89STNelZB4TiRNib1s24ednJJea7c/Uh065TDulN6BvcChHULZrBAniDqxiPwixRiLMsrW2/h1UkffVGwVTdrh9XlekWciORNL3e7qeec517xx0z+oz/2jqNbbSZA/DhWeIvW3giMMFa8vmg0rivrOjjBDGGE7Nhh5I+umOz3sMY3s3je87GfG4C0c1oL3t0pBWHPDGhxOrhU6PyHMPP4i/2oYNlqWx5gTvOYepou6ixzGgyrR18H90vW40wUOdTxFbjOea4lFdPBZuyVkgQUYitcj0XMSNGBGGQcVjM4X3LcUACuJaoOayQP9SP86OAuwkxBG2pa1yq5P+tzjSJl58Jo9kIVPaSl2ey4Y39PacPkCR7AWulZLjqF9mMI+lkUdcKXeOieBZxVaBBDkiJ5ieV0JsQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
